# Generated by Django 4.2 on 2025-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
